# Generated by Django 4.2.7 on 2025-06-26 20:08

import bursary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2024/2025', max_length=20, unique=True, verbose_name='academic year')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('application_deadline', models.DateTimeField(verbose_name='application deadline')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BursaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='application number')),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('tvet', 'TVET/Technical College'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20, verbose_name='education level')),
                ('institution_name_other', models.CharField(blank=True, max_length=200, verbose_name='institution name (if not listed)')),
                ('admission_number', models.CharField(max_length=50, verbose_name='admission/registration number')),
                ('course_name', models.CharField(help_text='e.g., Form 2, Bachelor of Science in Computer Science', max_length=200, verbose_name='course/class name')),
                ('year_of_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='year/form of study')),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total fees required')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount requested')),
                ('other_support', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='other financial support received')),
                ('family_monthly_income', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='family monthly income')),
                ('number_of_siblings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='number of siblings')),
                ('siblings_in_school', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='siblings in school')),
                ('is_orphan', models.BooleanField(default=False, verbose_name='orphan')),
                ('is_single_parent', models.BooleanField(default=False, verbose_name='single parent family')),
                ('has_disability', models.BooleanField(default=False, verbose_name='has disability')),
                ('special_circumstances', models.TextField(blank=True, help_text='Describe any special circumstances affecting your need for bursary', verbose_name='special circumstances')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='draft', max_length=20, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='approved amount')),
                ('reviewer_comments', models.TextField(blank=True, verbose_name='reviewer comments')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='bursary.academicyear')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bursary Application',
                'verbose_name_plural': 'Bursary Applications',
                'db_table': 'bursary_applications',
                'ordering': ['-created_at'],
                'permissions': [('can_review_application', 'Can review bursary application'), ('can_approve_application', 'Can approve bursary application'), ('can_disburse_funds', 'Can disburse bursary funds')],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='institution name')),
                ('institution_type', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('tvet', 'TVET/Technical College'), ('university', 'University'), ('other', 'Other')], max_length=20, verbose_name='type')),
                ('county', models.CharField(max_length=100, verbose_name='county')),
                ('address', models.TextField(verbose_name='address')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'db_table': 'institutions',
                'ordering': ['name'],
                'unique_together': {('name', 'county')},
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mpesa', 'M-PESA'), ('cash', 'Cash')], max_length=20, verbose_name='payment method')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='reference number')),
                ('paid_to', models.CharField(help_text='Name of institution or recipient', max_length=200, verbose_name='paid to')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='receipt number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='bursary.bursaryapplication')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disbursement',
                'verbose_name_plural': 'Disbursements',
                'db_table': 'disbursements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='bursary.institution'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=20, verbose_name='previous status')),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=20, verbose_name='new status')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='bursary.bursaryapplication')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Status Log',
                'verbose_name_plural': 'Application Status Logs',
                'db_table': 'application_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('admission_letter', 'Admission Letter'), ('fee_structure', 'Fee Structure'), ('transcript', 'Academic Transcript/Report Card'), ('id_copy', 'ID Card Copy'), ('birth_certificate', 'Birth Certificate'), ('parent_id', 'Parent/Guardian ID Copy'), ('death_certificate', 'Death Certificate (if orphan)'), ('disability_cert', 'Disability Certificate'), ('bank_slip', 'Bank Deposit Slip'), ('other', 'Other Supporting Document')], max_length=30, verbose_name='document type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('file', models.FileField(upload_to=bursary.models.application_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bursary.bursaryapplication')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'db_table': 'application_documents',
                'ordering': ['document_type', '-uploaded_at'],
            },
        ),
    ]
