# Generated by Django 4.2.7 on 2026-03-16 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_alter_bursaryapplication_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='academic_performance',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, verbose_name='average academic performance'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='annual_fees_per_structure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='annual fees as per fee structure (KES)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='app_guardian_address',
            field=models.CharField(blank=True, max_length=200, verbose_name="guardian's address"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='app_guardian_employment_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contractual', 'Contractual'), ('casual', 'Casual'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('none', 'None / Unemployed')], max_length=20, verbose_name="guardian's employment type"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='app_guardian_income_source',
            field=models.CharField(blank=True, max_length=200, verbose_name="guardian's main source of income"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='app_guardian_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="guardian's full name"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='app_guardian_occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name="guardian's occupation"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='app_guardian_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name="guardian's telephone"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='been_sent_away',
            field=models.BooleanField(default=False, verbose_name='have you been sent away from school?'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='campus_branch',
            field=models.CharField(blank=True, help_text='For tertiary institutions and universities', max_length=200, verbose_name='campus/branch'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chronic_illness_details',
            field=models.TextField(blank=True, verbose_name='chronic illness details'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='course duration (years)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='current_term_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="this semester/term's fee balance (KES)"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='disability_details',
            field=models.TextField(blank=True, help_text='If you have a disability, provide details', verbose_name='disability details'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='expected_completion',
            field=models.CharField(blank=True, max_length=10, verbose_name='expected completion (MM/YYYY)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='faculty_department',
            field=models.CharField(blank=True, help_text='For tertiary institutions and universities', max_length=200, verbose_name='faculty/department'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='family_annual_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estimated annual family expenses (KES)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='family_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estimated annual family income (KES)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='family_status',
            field=models.CharField(blank=True, choices=[('both_alive', 'Both Parents Alive'), ('one_dead', 'One Parent Dead'), ('both_dead', 'Both Parents Dead'), ('single_parent', 'Single Parent'), ('other', 'Other')], max_length=20, verbose_name='family status'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='family_status_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='other family status (specify)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_address',
            field=models.CharField(blank=True, max_length=200, verbose_name="father's address"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_employment_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contractual', 'Contractual'), ('casual', 'Casual'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('none', 'None / Unemployed')], max_length=20, verbose_name="father's employment type"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_income_source',
            field=models.CharField(blank=True, max_length=200, verbose_name="father's main source of income"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="father's full name"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name="father's occupation"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name="father's telephone"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='funding_source_college',
            field=models.CharField(blank=True, max_length=200, verbose_name='main funding source (college)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='funding_source_secondary',
            field=models.CharField(blank=True, max_length=200, verbose_name='main funding source (secondary)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='funding_source_university',
            field=models.CharField(blank=True, max_length=200, verbose_name='main funding source (university)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='has_chronic_illness',
            field=models.BooleanField(default=False, verbose_name='has chronic illness'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='helb_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HELB loan amount (where applicable)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='last_term_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="last semester/term's fee balance (KES)"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mode_of_study',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('parallel', 'Parallel'), ('boarding', 'Boarding'), ('day', 'Day Scholar')], max_length=20, verbose_name='mode of study'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_address',
            field=models.CharField(blank=True, max_length=200, verbose_name="mother's address"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_employment_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contractual', 'Contractual'), ('casual', 'Casual'), ('retired', 'Retired'), ('self_employed', 'Self Employed'), ('none', 'None / Unemployed')], max_length=20, verbose_name="mother's employment type"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_income_source',
            field=models.CharField(blank=True, max_length=200, verbose_name="mother's main source of income"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="mother's full name"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name="mother's occupation"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name="mother's telephone"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='next_term_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="next semester/term's fee balance (KES)"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='other_funding_college',
            field=models.CharField(blank=True, max_length=200, verbose_name='other funding (college)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='other_funding_secondary',
            field=models.CharField(blank=True, max_length=200, verbose_name='other funding (secondary)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='other_funding_university',
            field=models.CharField(blank=True, max_length=200, verbose_name='other funding (university)'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='parent_chronic_illness_details',
            field=models.TextField(blank=True, verbose_name='parent/guardian chronic illness details'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='parent_disability_details',
            field=models.TextField(blank=True, verbose_name='parent/guardian disability details'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='parent_has_chronic_illness',
            field=models.BooleanField(default=False, verbose_name='parent/guardian has chronic illness'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='parent_has_disability',
            field=models.BooleanField(default=False, verbose_name='parent/guardian has disability'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='previous_cdf_support',
            field=models.BooleanField(default=False, verbose_name='received NG-CDF bursary in the past?'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='previous_cdf_support_details',
            field=models.TextField(blank=True, verbose_name='if yes, specify amount and when'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='previous_other_support_details',
            field=models.TextField(blank=True, verbose_name='if yes, provide details'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='previous_other_support_received',
            field=models.BooleanField(default=False, verbose_name='received bursary from other organizations?'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='reason_for_applying',
            field=models.TextField(blank=True, verbose_name='why are you applying for bursary assistance?'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='referee1_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='referee 1 address'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='referee1_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='referee 1 name'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='referee1_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='referee 1 telephone'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='referee2_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='referee 2 address'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='referee2_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='referee 2 name'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='referee2_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='referee 2 telephone'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='sent_away_reasons',
            field=models.TextField(blank=True, verbose_name='reasons for absence'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='sent_away_weeks',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='weeks away from school'),
        ),
    ]
