# Generated by Django 4.2.7 on 2026-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_bursaryapplication_academic_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='declaration_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='declaration accepted at'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='guardian_declaration_accepted',
            field=models.BooleanField(default=False, help_text='Student confirms on behalf of parent/guardian', verbose_name='parent/guardian declaration accepted'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='guardian_signature',
            field=models.ImageField(blank=True, help_text='Upload an image of parent/guardian signature (optional)', upload_to='signatures/guardians/', verbose_name="parent/guardian's signature"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='student_declaration_accepted',
            field=models.BooleanField(default=False, help_text='Student confirms all information is true and accurate', verbose_name="student's declaration accepted"),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='student_signature',
            field=models.ImageField(blank=True, help_text='Upload an image of your signature (optional, for printed form)', upload_to='signatures/students/', verbose_name="student's signature"),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('transcript', "1. Student's Transcript / Report Form"), ('parent_id', "2. Parent's / Guardian's National ID Copy"), ('student_id', "3. Student's National ID Copy (mandatory post-school)"), ('birth_certificate', '4. Birth Certificate Copy'), ('school_id', '5. Secondary / College / University ID Card Copy'), ('death_certificate', '6. Death Certificate / Burial Permit (mandatory for orphans)'), ('fee_structure', '7. Current Fees Structure (mandatory for all)'), ('admission_letter', '8. Admission Letter (mandatory for colleges & universities)'), ('disability_cert', 'Disability Certificate'), ('medical_report', 'Medical Report / Chronic Illness Evidence'), ('chief_letter', 'Verification Letter from Area Chief / Sub-Chief'), ('recommendation_letter', 'Recommendation Letter'), ('bank_slip', 'Bank Deposit Slip'), ('other', 'Other Supporting Document')], max_length=30, verbose_name='document type'),
        ),
    ]
