# Generated by Django 4.2.7 on 2025-06-26 20:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code e.g. +254712345678', max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('id_number', models.CharField(help_text='Kenya National ID or Passport number', max_length=20, unique=True, verbose_name='ID/Passport Number')),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('admin', 'Admin'), ('reviewer', 'Reviewer'), ('approver', 'Approver')], default='applicant', max_length=20, verbose_name='role')),
                ('is_verified', models.BooleanField(default=False, help_text="Indicates if the user's phone number has been verified", verbose_name='verified')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='ward')),
                ('sub_county', models.CharField(blank=True, max_length=100, verbose_name='sub-county')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('sub_location', models.CharField(blank=True, max_length=100, verbose_name='sub-location')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='village')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='verification code')),
                ('is_used', models.BooleanField(default=False, verbose_name='used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'db_table': 'verification_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender')),
                ('guardian_name', models.CharField(blank=True, max_length=200, verbose_name='guardian/parent name')),
                ('guardian_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='guardian phone number')),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, verbose_name='relationship to guardian')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='emergency contact name')),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='emergency contact phone')),
                ('special_needs', models.TextField(blank=True, help_text='Describe any special needs or disabilities', verbose_name='special needs/disabilities')),
                ('id_card_front', models.ImageField(blank=True, upload_to='verification/id_cards/', verbose_name='ID card front')),
                ('id_card_back', models.ImageField(blank=True, upload_to='verification/id_cards/', verbose_name='ID card back')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
